### ISSUE TITLE
Add topics to repository

### ISSUE THREAD

**Issue by johnantoni** [ZeptoJS/Zepto.js#3]
Can we add topics to the repository, I don't have the power to do this at the moment but some topics I'd suggest are:

javascript, jquery, ajax, extension, library, effects, selector

**Comment by bmcminn** [comment]
@johnantoni just bumped your collaborator permissions to "Maintain", let me know if there are any other issues you have managing the repo.

I'll take a look at setting up some topics, but I'm not familiar with any standard mechanism in Github for these. How would you suggest doing this?

**Comment by johnantoni** [comment]
Thanks @bmcminn can you give me admin rights temporarily so I can try and add the topics, still having trouble?

**Comment by johnantoni** [comment]
thanks
