### ISSUE TITLE
Fix test builder

### ISSUE THREAD

**Issue by johnantoni** [ZeptoJS/Zepto.js#4]
At the moment it's linked to the original by madroby, needs to switched to a new one

https://travis-ci.org/madrobby/zepto

**Comment by johnantoni** [comment]
on this, just waiting for the organization to approve the request then I can get the test runners working again.

**Comment by bmcminn** [comment]
There were two requests, Travis CI and Travis CI for open source, went ahead and authorized the open-source option, but if the first needs it as well let me know.

**Comment by johnantoni** [comment]
thanks @bmcminn got travis working again.
