### ISSUE TITLE
Can you add me as a member of the organisation?

### ISSUE THREAD

**Issue by johnantoni** [ZeptoJS/Zepto.js#6]
Hi @bmcminn i'm setting up travis ci, can you add me as a member of the organization https://github.com/ZeptoJS

**Comment by bmcminn** [comment]
Just sent an invite, not sure if member permissions will allow for CI config, so we can elevate if needed

**Comment by johnantoni** [comment]
Thanks, got the invite. Can you elevate my permissions, don’t see it available.



On June 6, 2019 at 11:45:51 AM, Brandtley McMinn (notifications@github.com) wrote:

Just sent an invite, not sure if member permissions will allow for CI config, so we can elevate if needed

**Comment by johnantoni** [comment]
thanks @bmcminn got into travis-ci and sent a request to the organisation Zepto to allow it to connect.

If you see the request can you ok it and i'll then get travis hooked up and running, sorry looks like I can't do it as a organisation member.
